version: '3'
services:
  settingsservice:
    image: opennetwork/simplesettings-service:linux-amd64
    depends_on:
      - eventdb
    expose:
      - 80
    ports:
      - $SETTINGS_PORT:$SETTINGS_PORT
    env_file:
      - environment.${ENVIRONMENT_FILE}.env
      - ports.env
      - services.${SERVICES_FILE}.env
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=~^/api/settings
      - JWT_PUB_KEY=$JWT_PUB_KEY
    restart: always
    volumes:
      - ${DATA_LOC}/settings:/data
